version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
- package-ecosystem: npm
  directory: "/packages/backend"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
- package-ecosystem: npm
  directory: "/packages/client"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
